### ISSUE TITLE
Resolving to cell line name with forward slash in name

### ISSUE THREAD

**Issue by dbarrell** [assefamaru/cellosaurus-api#2]
Hi. How would one get a endpoint to resolve with a forward slash in the name, e.g. PC-9/GR5? For instance how does the following get resolved to a slash serverside?

https://api.cellosaur.us/v34/cell_lines/pc-9**%2F**gr5

Currently it returns:
400 Client Error: Bad Request for url: https://api.cellosaur.us/v34/cell_lines/PC-9/GR5

Thanks!

**Comment by assefamaru** [comment]
Hi @dbarrell, thanks for pointing out this bug. 

I've upated the routes to use [gin's](https://github.com/gin-gonic/gin#parameters-in-path) optional parameters, so your example above, and any other cell lines with slashes in them should now resolve. Let me know if you encounter any other special names that don't resolve properly.

Thanks!
